; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

; Inno Setup Script para Password Saver
; Author: JC && chatgpt

[Setup]
AppName=Password Saver
AppVersion=2.2.0
DefaultDirName={sd}\Password Saver
DisableProgramGroupPage=yes
OutputBaseFilename=PasswordSaverInstaller
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
SetupIconFile=<baseDir>\PasswordSaverNET\bin\Release\net8.0-windows10.0.19041.0\win10-x64\publish\favicon.ico
Compression=lzma
SolidCompression=yes
OutputDir=C:\Installers

[Languages]
Name: "english"; MessagesFile:"compiler:Default.isl"

[Files]
Source: "<baseDir>\PasswordSaverNET\bin\Release\net8.0-windows10.0.19041.0\win10-x64\publish\PasswordSaver.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "<baseDir>\PasswordSaverNET\bin\Release\net8.0-windows10.0.19041.0\win10-x64\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; Start menu
Name: "{group}\Password Saver"; Filename: "{app}\PasswordSaver.exe"
; Desktop
Name: "{commondesktop}\Password Saver"; Filename: "{app}\PasswordSaver.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Crear acceso directo en el escritorio"; GroupDescription: "Accesos directos:"

[Run]
Filename: "{app}\PasswordSaver.exe"; Description: "Execute Password Saver"; Flags: nowait postinstall skipifsilent
