<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SelfContained>true</SelfContained>
  </PropertyGroup>

  <ItemGroup>
		<Compile Remove="browser\**" />
    <Content Include="browser\**">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
	</ItemGroup>
<!-- 
  <ItemGroup>
		<Compile Remove="Resources\**" />
    <Content Include="Resources\**">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
	</ItemGroup> -->

<ItemGroup>
  <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
  <PackageReference Include="EmbedIO" Version="3.5.2" />
  <PackageReference Include="GirCore.Gtk-4.0" Version="0.7.0" />
  <PackageReference Include="GirCore.WebKit-6.0" Version="0.7.0" />
  <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.2" />
  <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
</ItemGroup>
</Project>
